language: php
cache:
  directories:
    - $HOME/.composer/cache/files
php:
- 7.2
before_script:
- cp .env.testing .env
- touch database/database.sqlite
- composer self-update
- composer install --no-interaction
script:
- php artisan key:generate
- php artisan storage:link
- vendor/bin/phpunit --coverage-clover=coverage.xml
notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
